spring:
  datasource:
    url: jdbc:h2:mem:openapidb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  mail:
    host: localhost
    port: 1025
    username: noop@localhost
    password: noop
  security:
    user:
      name: admin
      password: admin

jwt:
  secret: dGVzdC1zZWNyZXQta2V5LXRoYXQtaXMtbG9uZy1lbm91Z2gtZm9yLWhzMjU2
  expiration: 3600000

minio:
  endpoint: http://localhost
  port: 9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: test-bucket

frontend:
  url: http://localhost:3000
